### ISSUE TITLE
Round wins

### ISSUE THREAD

**Issue by oivindth** [Andrioden/gnstats#44]
Make it possible to filter on "round wins". On each game round, the person with the highest score gets a win. Add a Round wins filter on top, i.e: 

Stian: 20
Damian: 15
Ole: 10
Øivind: 5
Andre: 0

Also make it possible to filter round wins on year etc.

**Comment by Andrioden** [comment]
Cool idea. Will implement this!

And

Fuck you! : p

**Comment by Andrioden** [comment]
Implementation details:
- Star next to date if round win
- Need to make a new page "Stats" that contains this data. Or so

**Comment by Andrioden** [comment]
For the future: Decided against not adding some indication on rounds on who won. For now. Requires to implement some post-save-vote recalc of stats for each game. Not feelin it atm.
