### ISSUE TITLE
Add participators when creating game night

### ISSUE THREAD

**Issue by oivindth** [Andrioden/gnstats#50]
When creating game nights, you have to add who was participating to avoid the missing person having to vote.

**Comment by Andrioden** [comment]
I think instead i will allow a checkbox "not present" when someone is away. And then vote score is not needed. However i think this wont work well with the stats calculation atm. So might require some rewrite. So leaving this as an improvement for the future.

**Comment by Andrioden** [comment]
Idea:
- [ ] Can set not present in game night
- [ ] Average for not present people is calculated and saved when all have votet or is set not present

**Comment by oivindth** [comment]
proposal: When person is not present, calulcate score based on 4 instead of 5.
